### ISSUE TITLE
shadow passwd

### ISSUE THREAD

**Issue by Jo7e4** [joaomdsc/lfs#1]
really nice job on these scripts! One issue i found is that after installing the shadow tarball, the pwconv and grpconv are not being run, so the /etc/passwd and /etc/group keep the encrypted root passwords.

**Comment by Jo7e4** [comment]
Aah i see that's intentional:
'6.24': [
        (7, 'ignore'),  # don't enable shadowed passwords
        (8, 'ignore'),  # don't enable shadowed group passwords

Never mind ;)

**Comment by joaomdsc** [comment]
Thanks for the feedback :-) Yes, that 'directives' file is there to let you configure the system the way you want it. Don't hesitate to drop me a note if you find any other issues.

**Comment by Jo7e4** [comment]
Absolutely love it :) Built 2 systems with it in qemu which i transplanted (with another kernel) to my main PC. (with a little grub and qemu-fu). 

I tried to hack the script a bit to let it parse the svn versions of the book and also some URL's of the BLFS book, but my python knowledge is limited so haven't succeded there yet ;) I'll have another go at it when i have a GUI running on my main system (based on LFS created with your scripts ;) 

Thanks a lot for sharing this!
